name: linkedin_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  google_sign_in: ^5.4.2
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
